import Head from 'next/head';
import Todo from '../Components/Todo';
import { useEffect, useState } from 'react';
import Header from '../Components/Header';
import Sidebar from '../Components/Sidebar';

export default function Home() {
  const [openMenu, setOpenMenu] = useState<boolean>(true);

  useEffect(() => {
    setOpenMenu(window.innerWidth > 767 ? true : false);
  }, []);

  return (
    <div className='h-screen'>
      <Head>
        <title>Welcome to Todo App</title>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='h-full'>
        <Header />
        <div className='h-full flex md:flex-col md:w-full'>
          <div className='md:text-right md:pr-2 md:my-4 hidden md:inline-block'>
            <span
              className='text-right text-xs text-lightText'
              onClick={() => setOpenMenu(!openMenu)}
            >
              {openMenu ? 'Close Menu' : 'Open Menu'}
            </span>
          </div>
          <div>
            <Sidebar openMenu={openMenu} />
          </div>
          <Todo />
        </div>
      </div>
    </div>
  );
}
